version: '3.7'
services:
  zwave2mqtt:
    image: robertslando/zwave2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - 'zwave2mqtt:/usr/src/app/store'
    ports:
      - '8091:8091'
volumes:
  zwave2mqtt:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.2,rw,nolock,soft
      device: ':/volume1/docker/zwave2mqtt'

